all:count test1
count: count.cpp ll.h
	g++ -o count -ggdb3 -Wall -Werror -pedantic -std=gnu++98 count.cpp

test1: test-lls.cpp ll.h
	g++ -o test1 -ggdb3 -Wall -Werror -pedantic -std=gnu++98 test-lls.cpp
